"""Interface facade for stable imports."""

from dare_framework3.interfaces.kernel import (
    IRunLoop,
    ILoopOrchestrator,
    IExecutionControl,
    IResourceManager,
    IEventLog,
    IExtensionPoint,
    IContextManager,
    ISecurityBoundary,
    IToolGateway,
)
from dare_framework3.interfaces.components import (
    IHook,
    IContextStrategy,
    IMemory,
    IPromptStore,
    IRetriever,
    IIndexer,
    ITrustVerifier,
    IPolicyEngine,
    ISandbox,
    ITool,
    ICapabilityProvider,
    ISkill,
    IPlanner,
    IValidator,
    IRemediator,
    IModelAdapter,
)

__all__ = [
    "IRunLoop",
    "ILoopOrchestrator",
    "IExecutionControl",
    "IResourceManager",
    "IEventLog",
    "IExtensionPoint",
    "IContextManager",
    "ISecurityBoundary",
    "IToolGateway",
    "IHook",
    "IContextStrategy",
    "IMemory",
    "IPromptStore",
    "IRetriever",
    "IIndexer",
    "ITrustVerifier",
    "IPolicyEngine",
    "ISandbox",
    "ITool",
    "ICapabilityProvider",
    "ISkill",
    "IPlanner",
    "IValidator",
    "IRemediator",
    "IModelAdapter",
]
